
---
- hosts: ios
  gather_facts: no
  connection: local

  tasks:
     - name: Get BGP AS from POLICE VRF 
       set_fact:
         bgp_as_list: "{{ vrfs[0].route_import | bgp_as_from_rt }}"

     - name: Print resulting list
       debug:
         msg: "{{ bgp_as_list }}"
